def get_nta_name(neighbourhood: str) -> str:
    new_names = {
        "Baychester": "Eastchester-Edenwald-Baychester",
        "Bronxdale": "Bronx Park",
        "Castle Hill": "Castle Hill-Unionport",
        "City Island": "Pelham Bay-Country Club-City Island",
        "Claremont Village": "Claremont Village-Claremont (East)",
        "Clason Point": "Soundview-Clason Point",
        "Concourse": "East Concourse-Concourse Village",
        "Concourse Village": "East Concourse-Concourse Village",
        "East Morrisania": "Morrisania",
        "Eastchester": "Eastchester-Edenwald-Baychester",
        "Edenwald": "Eastchester-Edenwald-Baychester",
        "Fieldston": "Riverdale-Spuyten Duyvil",
        "Fordham": "Fordham Heights",
        "Kingsbridge": "Kingsbridge Heights",
        "Morris Heights": "University Heights (South)-Morris Heights",
        "Mott Haven": "Mott Haven-Port Morris",
        "Mount Eden": "Mount Eden-Claremont (West)",
        "North Riverdale": "Riverdale-Spuyten Duyvil",
        "Olinville": "Williamsbridge-Olinville",
        "Pelham Bay": "Pelham Bay-Country Club-City Island",
        "Port Morris": "Mott Haven-Port Morris",
        "Riverdale": "Riverdale-Spuyten Duyvil-Fieldston",
        "Schuylerville": "Schuylerville-Throgs Neck-Edgewater Park",
        "Soundview": "Soundview-Bruckner",
        "Spuyten Duyvil": "Riverdale-Spuyten Duyvil-Fieldston",
        "Throgs Neck": "Schuylerville-Throgs Neck-Edgewater Park",
        "Unionport": "Soundview-Bruckner",
        "University Heights": "University Heights (North)-Fordham",
        "Van Nest": "Van Nest-Morris Park-Westchester Square",
        "Wakefield": "Wakefield-Woodlawn",
        "Williamsbridge": "Williamsbridge-Olinville",
        "Woodlawn": "Wakefield-Woodlawn",
        "Bedford-Stuyvesant": "Bedford",
        "Bergen Beach": "Georgetown-Marine Park-Bergen Beach-Mill Basin",
        "Boerum Hill": "DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill",
        "Bushwick": "Bushwick North",
        "Carroll Gardens": "Carroll Gardens-Columbia Street-Red Hook",
        "Cobble Hill": "Brooklyn Heights-Cobble Hill",
        "Columbia St": "Carroll Gardens-Columbia Street-Red Hook",
        "Coney Island": "Coney Island-Sea Gate",
        "Crown Heights": "Crown Heights North",
        "DUMBO": "DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill",
        "Downtown Brooklyn": "DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill",
        "East Flatbush": "East Flatbush-Farragut",
        "East New York": "East New York",
        "Gowanus": "Park Slope-Gowanus",
        "Gravesend": "Gravesend",
        "Manhattan Beach": "Sheepshead Bay-Gerritsen Beach-Manhattan Beach",
        "Mill Basin": "Georgetown-Marine Park-Bergen Beach-Mill Basin",
        "Navy Yard": "DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill",
        "Prospect-Lefferts Gardens": "Prospect Lefferts Gardens-Wingate",
        "Red Hook": "Carroll Gardens-Columbia Street-Red Hook",
        "Sea Gate": "Coney Island-Sea Gate",
        "Sheepshead Bay": "Sheepshead Bay-Gerritsen Beach-Manhattan Beach",
        "South Slope": "Park Slope-Gowanus",
        "Sunset Park": "Sunset Park West",
        "Vinegar Hill": "DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill",
        "Windsor Terrace": "Windsor Terrace",
        "Battery Park City": "Battery Park City-Lower Manhattan",
        "Chelsea": "Hudson Yards-Chelsea-Flatiron-Union Square",
        "Chinatown": "Chinatown",
        "Civic Center": "SoHo-TriBeCa-Civic Center-Little Italy",
        "East Harlem": "East Harlem North",
        "Financial District": "Battery Park City-Lower Manhattan",
        "Flatiron District": "Hudson Yards-Chelsea-Flatiron-Union Square",
        "Harlem": "Central Harlem",
        "Kips Bay": "Murray Hill-Kips Bay",
        "Little Italy": "SoHo-TriBeCa-Civic Center-Little Italy",
        "Marble Hill": "Marble Hill-Inwood",
        "Midtown": "Midtown-Midtown South",
        "Murray Hill": "Murray Hill-Kips Bay",
        "NoHo": "West Village",
        "Nolita": "SoHo-TriBeCa-Civic Center-Little Italy",
        "Roosevelt Island": "Roosevelt Island",
        "SoHo": "SoHo-TriBeCa-Civic Center-Little Italy",
        "Stuyvesant Town": "Stuyvesant Town-Cooper Village",
        "Theater District": "Midtown-Midtown South",
        "Tribeca": "SoHo-TriBeCa-Civic Center-Little Italy",
        "Two Bridges": "Chinatown",
        "Upper East Side": "Upper East Side-Carnegie Hill",
        "Upper West Side": "Upper West Side",
        "Washington Heights": "Washington Heights North",
        "Arverne": "Hammels-Arverne-Edgemere",
        "Astoria": "Astoria",
        "Bay Terrace": "Bayside-Bayside Hills",
        "Bayswater": "Far Rockaway-Bayswater",
        "Belle Harbor": "Neponsit-Belle Harbor-Rockaway Park",
        "Breezy Point": "Breezy Point-Belle Harbor-Rockaway Park-Broad Channel",
        "Briarwood": "Briarwood-Jamaica Hills",
        "Ditmars Steinway": "Astoria",
        "Douglaston": "Douglas Manor-Douglaston-Little Neck",
        "Edgemere": "Hammels-Arverne-Edgemere",
        "Far Rockaway": "Far Rockaway-Bayswater",
        "Flushing": "Flushing",
        "Fresh Meadows": "Fresh Meadows-Utopia",
        "Holliswood": "Jamaica Estates-Holliswood",
        "Howard Beach": "Ozone Park",
        "Jamaica Estates": "Jamaica Estates-Holliswood",
        "Jamaica Hills": "Briarwood-Jamaica Hills",
        "Little Neck": "Douglas Manor-Douglaston-Little Neck",
        "Long Island City": "Hunters Point-Sunnyside-West Maspeth",
        "Neponsit": "Neponsit-Belle Harbor-Rockaway Park",
        "Rockaway Beach": "Hammels-Arverne-Edgemere",
        "Springfield Gardens": "Springfield Gardens North",
        "Whitestone": "Whitestone",
        "Arden Heights": "Arden Heights",
        "Arrochar": "Grasmere-Arrochar-South Beach",
        "Bay Terrace, Staten Island": "Bay Terrace-Utopia",
        "Bull's Head": "New Springville-Bloomfield-Travis",
        "Castleton Corners": "Westerleigh",
        "Clifton": "Stapleton-Rosebank",
        "Concord": "Grasmere-Arrochar-South Beach",
        "Dongan Hills": "Old Town-Dongan Hills-South Beach",
        "Eltingville": "Great Kills-Eltingville",
        "Emerson Hill": "Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill",
        "Graniteville": "Mariner's Harbor-Arlington-Port Ivory-Graniteville",
        "Grant City": "Old Town-Dongan Hills-South Beach",
        "Great Kills": "Great Kills",
        "Grymes Hill": "Grymes Hill-Clifton-Fox Hills",
        "Howland Hook": "Mariner's Harbor-Arlington-Port Ivory-Graniteville",
        "Huguenot": "Charleston-Richmond Valley-Tottenville",
        "Lighthouse Hill": "Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill",
        "Mariners Harbor": "Mariner's Harbor-Arlington-Port Ivory-Graniteville",
        "Midland Beach": "Old Town-Dongan Hills-South Beach",
        "New Brighton": "West New Brighton-New Brighton-St. George",
        "New Dorp": "New Dorp-Midland Beach",
        "New Dorp Beach": "New Dorp-Midland Beach",
        "New Springville": "New Springville-Bloomfield-Travis",
        "Oakwood": "Oakwood-Oakwood Beach",
        "Prince's Bay": "Annadale-Huguenot-Prince's Bay-Woodrow",
        "Randall Manor": "West New Brighton-New Brighton-St. George",
        "Richmondtown": "Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill",
        "Rosebank": "Stapleton-Rosebank",
        "Rossville": "Arden Heights",
        "Shore Acres": "Grasmere-Arrochar-South Beach",
        "Silver Lake": "Port Richmond",
        "South Beach": "Grasmere-Arrochar-South Beach",
        "St. George": "West New Brighton-New Brighton-St. George",
        "Stapleton": "Stapleton-Rosebank",
        "Todt Hill": "Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill",
        "Tompkinsville": "Stapleton-Rosebank",
        "Tottenville": "Charleston-Richmond Valley-Tottenville",
        "West Brighton": "West New Brighton-New Brighton-St. George",
        "Westerleigh": "Westerleigh",
        "Willowbrook": "Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill",
        "Woodrow": "Annadale-Huguenot-Prince's Bay-Woodrow"
    }

    if neighbourhood in new_names.keys():
        return new_names[neighbourhood]
    return neighbourhood


def model(dbt, session):
    listings_df = dbt.ref("bronze_listings").df()
    neighbourhoods_df = listings_df[listings_df["neighbourhood_group", "neighbourhood"]].unique()
    neighbourhoods_df["nta_name"] = neighbourhoods_df["neighbour"].apply(get_nta_name)
    return neighbourhoods_df
